trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

jobs:
- template: job--pre-commit.yml
- template: job--python-tox.yml
  parameters:
    coverage: false
    toxenvs: [py27, py34, py35, py36, py37, py38, pypy, pypy3, docs]
